### ISSUE TITLE
Missing get categories recursively

### ISSUE THREAD

**Issue by Daniel304** [clockworkgeek/Magento-Extra-RESTful#1]
I truely love this extension and made my work a lot easier.
However the only thing I am missing is retrieving the full list of categories recursively.. it already has a parent id so it can just as easy be recursive..

**Comment by clockworkgeek** [comment]
You may already call `GET /api/rest/categories/parent/:parent` recursively to build a tree. Were you expecting a ready-made tree instead?

**Comment by at1989** [comment]
Very helpful but facing a problem .This is working in localhost but not working in staging server. Firstly i had tested this extension on localhost, it has been working smoothly but its not working on staging server . Even i had followed the same instructions or path as i did on localhost .Please help.
