### ISSUE TITLE
Not working on staging server !

### ISSUE THREAD

**Issue by at1989** [clockworkgeek/Magento-Extra-RESTful#2]
Very helpful but facing a problem .This is working in localhost but not working in staging server. Firstly i had tested this extension on localhost, it has been working smoothly but its not working on staging server . Even i had followed the same instructions or path as i did on localhost .Please help.

**Comment by clockworkgeek** [comment]
There must be some difference between the two servers.  Please remember to clear the staging server's cache and recompile if you're using that feature.  Look for specific errors and copy them here, in full.  Without more information there is nothing I can do to help.

**Comment by at1989** [comment]
Hello,

Its working dear thanks.

There is one thing i want to ask you that, how to get category tree i.e
parent category and all its child categories ?
I want to retrieve category tree with default category as parent category.
Like below example
[image: Inline image 1]

**Comment by at1989** [comment]
Its working .Thanks
