### ISSUE TITLE
How to get category tree ?

### ISSUE THREAD

**Issue by at1989** [clockworkgeek/Magento-Extra-RESTful#3]
There is one thing i want to ask you that, how to get category tree i.e
parent category and all its child categories ?
I want to retrieve category tree with default category as parent category.
Like below example
![image](https://user-images.githubusercontent.com/36258652/36016190-ca34df7e-0d97-11e8-9876-0643c8d63d5b.png)

**Comment by Daniel304** [comment]
You will have to do it by yourself unfortunately it can be quite calll intensive if you have a lot of subcategories. I will post an excerpt of my code in about 15 minutes.

**Comment by at1989** [comment]
I am waiting for you code and also trying to build my own .

**Comment by Daniel304** [comment]
`  def index
    @array_of_cats      = []
    root_category       = 2
    get_child_cats(root_category)
  med

  def get_child_cats(category_id)
    response           = service.connect('GET','https://www.xxx.com/api/rest/categories/parent/' + category_id.to_s)
    categories         = JSON.parse(response.body)
    categories.each do | category |
      @array_of_cats << category
      get_child_cats(category[0].to_i,service) if category[1]['children_count'].to_i > 0
    end
  end
`

**Comment by clockworkgeek** [comment]
I see this is a worthwhile feature so I will add it, at some time...

**Comment by Daniel304** [comment]
That would be great (see issue #1)

**Comment by at1989** [comment]
I am a beginner , can you explain the code ?

**Comment by at1989** [comment]
Actually i am getting the category by thus code 
protected function _getCategories()
    {
        /* @var $categories Mage_Catalog_Model_Resource_Category_Collection */
        $categories = Mage::getResourceModel('catalog/category_collection');
        $categories->setStoreId($this->getRequest()->getParam('store'));
        if (($parentId = $this->getRequest()->getParam('parent'))) {
            $categories->addAttributeToFilter('parent_id', $parentId);
        }
        $categories->addAttributeToSelect(array_keys(
            $this->getAvailableAttributes($this->getUserType(), Mage_Api2_Model_Resource::OPERATION_ATTRIBUTE_READ)
        ));
        // global root must always be hidden
        $categories->addFieldToFilter('path', array('neq' => '1'));
        // if not admin, filter is_active
        if (Mage_Api2_Model_Auth_User_Admin::USER_TYPE != $this->getUserType()) {
            $categories->addIsActiveFilter();
        }
        $this->_applyCollectionModifiers($categories);
        return $categories;
    }

**Comment by at1989** [comment]
But not getting the desired result

**Comment by at1989** [comment]
I want full category tree as mentioned in the above posted picture

**Comment by at1989** [comment]
And i am calling it by the following code :

$oauthClient = new OAuth($consumerKey, $consumerSecret, OAUTH_SIG_METHOD_HMACSHA1);
$oauthClient->setToken($token, $tokensecret);
$oauthClient->enableDebug();          

$resourceUrl = "https://mydomain/api/rest/categories";
$oauthClient->fetch($resourceUrl, array() , 'GET',  array('Content-Type' => 'application/json', 'Accept' => '*/*'));
					$responseArr = json_decode($oauthClient->getLastResponse());
					echo '<pre>';print_r($responseArr);die;
					echo json_encode($responseArr);

**Comment by Daniel304** [comment]
what you should do is creating a loop going over each category checking if it has children and then calling function _getCategories with the 'parent' category. Adding the results to the first array... you won't really get a hierarchical array but it will get you all the subcategories..

**Comment by at1989** [comment]
I am  not  getting it, Please help. Here is my code please  modify it to make category tree 
Category.php

<?php
/**
 * Generic API methods here, specialise elsewhere
 */
class ANIL_CustomRest_Model_Api2_Category extends Mage_Api2_Model_Resource
{
    /**
     * Retrieve single category by entity ID
     * 
     * @return array
     */
    protected function _retrieve()
    {
        $category = $this->_getCategory();
        if (! $category->getIsActive()) {
            $this->_critical(self::RESOURCE_NOT_FOUND);
        }
        return $category->getData();
    }
    /**
     * @return Mage_Catalog_Model_Category
     */
    protected function _getCategory()
    {
        /* @var $category Mage_Catalog_Model_Category */
        $category = Mage::getModel('catalog/category');
        $category->setStoreId($this->getRequest()->getParam('store'));
        $categoryId = $this->getRequest()->getParam('id');
        $category->load($categoryId);
        if (! $category->getId()) {
            $this->_critical(self::RESOURCE_NOT_FOUND);
        }
        return $category;
    }
    protected function _retrieveCollection()
    {
        $data = $this->_getCategories()->load()->toArray();
        return isset($data['items']) ? $data['items'] : $data;
    }
    /**
     * @return Mage_Catalog_Model_Resource_Category_Collection
     */
    protected function _getCategories()
    {
        /* @var $categories Mage_Catalog_Model_Resource_Category_Collection */
        $categories = Mage::getResourceModel('catalog/category_collection');
        $categories->setStoreId($this->getRequest()->getParam('store'));
        if (($parentId = $this->getRequest()->getParam('parent'))) {
            $categories->addAttributeToFilter('parent_id', $parentId);
        }
        $categories->addAttributeToSelect(array_keys(
            $this->getAvailableAttributes($this->getUserType(), Mage_Api2_Model_Resource::OPERATION_ATTRIBUTE_READ)
        ));
        // global root must always be hidden
        $categories->addFieldToFilter('path', array('neq' => '1'));
        // if not admin, filter is_active
        if (Mage_Api2_Model_Auth_User_Admin::USER_TYPE != $this->getUserType()) {
            $categories->addIsActiveFilter();
        }
        $this->_applyCollectionModifiers($categories); 
        return $categories;
    }
    /**
     * @see Mage_Customer_Model_Api2_Customer::_getResourceAttributes()
     */
    protected function _getResourceAttributes()
    {
        return $this->getEavAttributes(true, true);
    }
}

**Comment by clockworkgeek** [comment]
There is no need for multiple calls, all the information you need is available from one `GET /api/rest/categories` or `GET /api/rest/categories/store/:store`.  Here is a sample I just tried for proof.

```
<?php
// API needs an Accept header to assume JSON type
$context = stream_context_create(['http' => ['header' => 'Accept: */*']]);
// quick and dirty, no error checking
$response = file_get_contents('http://localhost/api/rest/categories/store/default', false, $context);
// decode as flat array
$categories = json_decode($response, true);

// build tree association using array references
foreach ($categories as &$category) {
    // note the root node
    if (@$category['level'] <= 1) {
        $root = $category['entity_id'];
    }
    // add to parent node
    elseif ($parent = @$category['parent_id']) {
        $categories[$parent]['children'][] = &$category;
    }
}

// dump it and see
print_r(@$categories[$root]);
```

**Comment by clockworkgeek** [comment]
I'm considering a larger feature because the above is lacking in some details.  For example it doesn't apply a sort order, it's affected by the API's inherent page size limit, and I'm not convinced the root category needs to be visible.  If you gentlemen have any experience to share it will be welcome.  In particular I'd like to know how you make the association from category to product.  Does the API have a way to list products for a given category?

**Comment by Daniel304** [comment]
The limit sucks but you can circumvent the limit by giving adding limit=20000 it to the post parameters.
If you have multiple roots like we do it can come in handy....
You can get all products for a given category like this: GET /products/category_id=:id

**Comment by clockworkgeek** [comment]
That's not as bad as I feared.  The [devdocs](http://devdocs.magento.com/guides/m1x/api/rest/introduction.html) don't mention that `category_id` is possible.  You've caused me to think about multi-store situations and how nice it would be to associate categories with stores...

**Comment by at1989** [comment]
Yes , we have maximum limit 100 so cant get category tree in a single page, Because i have around 800 categories to fetch,,,,,
And one more thing ,
how to get products of a particular id ?
I mean something like category/:cat_id/products

**Comment by Daniel304** [comment]
http://devdocs.magento.com/guides/m1x/api/rest/Resources/Products/products.html#RESTAPI-Resource-Products-HTTPMethod-GET-products-categoryid--id

**Comment by clockworkgeek** [comment]
Many thanks to both of you.  I am learning a lot today.

**Comment by Daniel304** [comment]
Here is how you can change the max limit
https://stackoverflow.com/questions/16726514/magento-errors-limit-100-reached-how-to-increase-limit

**Comment by clockworkgeek** [comment]
Hmm, it seems the limit may actually be `Mage_Api2_Model_Resource::PAGE_SIZE_MAX`.

**Comment by clockworkgeek** [comment]
Hello all,

I believe I now have a satisfactory solution.  To make it easier to control permissions the new category tree is a separate resource (`/api/rest/category_trees`) so you may need to enable it in _System > Web Services > REST - Roles_.  This resource is read-only and inherits attributes from `/api/rest/categories` so you don't need to enable any more of those.  This should meet all points mentioned above and some more concerns of my own.  Please see 2500155 for a few more details.
