### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by Daseraf** [clockworkgeek/Magento-Extra-RESTful#4]
Good day! I have an error while performing a GET request:
http://ros-cocos.ru/api/rest/products/9?attrs=color
ONLY PHP 7.0.29
 PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Mage_Api2_Model_Acl_Filter::_filter() must be of the type array, null given, called in /var/www/www-root/data/www/ros-cocos.ru/app/code/core/Mage/Api2/Model/Acl/Filter.php on line 191 and defined in /var/www/www-root/data/www/ros-cocos.ru/app/code/core/Mage/Api2/Model/Acl/Filter.php:74\nStack trace:\n#0 /var/www/www-root/data/www/ros-cocos.ru/app/code/core/Mage/Api2/Model/Acl/Filter.php(191): Mage_Api2_Model_Acl_Filter->_filter(NULL, Array)\n#1 /var/www/www-root/data/www/ros-cocos.ru/app/code/core/Mage/Api2/Model/Resource.php(240): Mage_Api2_Model_Acl_Filter->out(Array)\n#2 /var/www/www-root/data/www/ros-cocos.ru/app/code/community/Clockworkgeek/Extrarestful/Model/Api2/Abstract.php(128): Mage_Api2_Model_Resource->dispatch()\n#3 /var/www/www-root/data/www/ros-cocos.ru/app/code/core/Mage/Api2/Model/Dispatcher.php(74): Clockworkgeek_Extrarestful_Model_Api2_Abstract->dispatch()\n#4 /var/www/www-root/data/www/ros-cocos.ru/app/code/core/Mage/Api2/Model/Server.php(239): Mage_Api2_M in /var/www/www-root/data/www/ros-cocos.ru/app/code/core/Mage/Api2/Model/Acl/Filter.php on line 74

**Comment by clockworkgeek** [comment]
Thank you for your report and also for including the stack trace.  I tried with a similar version of PHP and [HTTPie](https://httpie.org/) and could not immediately recreate the problem.
```
$ http magento-1-9.dev/api/rest/products/37?attrs=color
HTTP/1.1 200 OK
Cache-Control: public,max-age=86400
Content-Length: 17
Content-Type: application/json; charset=utf-8
Date: Thu, 26 Apr 2018 19:10:09 GMT
Last-Modified: Thu, 16 May 2013 20:18:08 GMT
Server: Apache
Vary: Accept,Authorization,Version
X-Powered-By: PHP/7.0.27

{
    "color": "Black"
}
```
However the error you see could happen if none of the `attrs` were enabled in _System > Web Services > REST - Attributes > Guest_.  I tried again with the path `/api/rest/products/37?attrs=nonexistent` and this time did get the same error, but only with PHP 7 as you point out.  The same thing happens with core Magento resources so it's not limited to this extension.  In this case the answer is to enable the `color` attribute for each API user.

**Comment by Daseraf** [comment]
I don't have access to the custom attributes for the Guest and client in REST - Attributes - Guest. Only default attributes xD

**Comment by clockworkgeek** [comment]
Please go to _Catalog > Attributes > Manage Attributes_.  For the "Color" attribute is "Visible on Product View Page on Front-end" set to "Yes"?  From my understanding it must be or it will not be selectable for the API either, which sort of makes sense.

**Comment by Daseraf** [comment]
It's all good! Thank you!
