### ISSUE TITLE
How to get product by sku? 

### ISSUE THREAD

**Issue by Daseraf** [clockworkgeek/Magento-Extra-RESTful#5]
Hi! You have not implemented query functionality of a product by its sku?

**Comment by clockworkgeek** [comment]
You can also use `attrs` query parameter at the same time, e.g.
http://ros-cocos.ru/api/rest/products?filter[1][attribute]=sku&filter[1][in]=iPhone&attrs=entity_id,name,url

**Comment by Daseraf** [comment]
Costum attribute "memorys" is not showing =(
http://ros-cocos.ru/api/rest/products?filter%5B1%5D%5Battribute%5D=sku&filter%5B1%5D%5Bin%5D=iPhone&attrs=memorys,name
