### ISSUE TITLE
Associated Products problem

### ISSUE THREAD

**Issue by Daseraf** [clockworkgeek/Magento-Extra-RESTful#6]
If simple products were not created during the creation configureimage of the item, it displays the JSON is empty or the data is not displayed.
Incomplete output in JSON
https://tradeinmobile.ru/api/rest/products/49/associated
in catalog:
https://tradeinmobile.ru/katalog/iphone-7.html

Empty:
https://tradeinmobile.ru/api/rest/products/152/associated
in catalog:
https://tradeinmobile.ru/katalog/iphone-x.html

1.9.3.8

**Comment by clockworkgeek** [comment]
Hi,
Are you creating both configurable and simple products through this API? Is there a notice in admin like "One or more indexes are out of date"? Lists of products in this extension use the flattened tables for speed, does reindexing the "Product Flat Data" have an effect?

**Comment by Daseraf** [comment]
I tried to associate the items via Magento Admin Panel, Magento Store Manager, Default Import/Export = no effect. Disable/Enable Flat Data and indexing = no effect. Indexing via shell = no effect. Associated products appear in the JSON /associated only if you create them together with a configurable item in the settings of the configurable product, and only if you use a full Manager, not quick create.

**Comment by Daseraf** [comment]
After removal and import of products using Default Import/export all associations disappeared in the JSON. In the catalog everything is fine. After you remove/import via magento manager partially installed Association. Trying Magmi

**Comment by clockworkgeek** [comment]
The associated products only show if they have an image.  For example, this URL returns an empty list, `https://tradeinmobile.ru/api/rest/products/152/associated` whereas this URL returns a list of names, `https://tradeinmobile.ru/api/rest/products/152/associated?attrs=name`.  This is because `attrs` does not include `image_url` so the image field is not joined.  I must change the join to a left join to prevent this from happening and will do so later today.

**Comment by Daseraf** [comment]
All right, once I added the image, JSON started to take shape. However seen printed no more than 10 indexes, while the I have 18.
https://tradeinmobile.ru/api/rest/products/153/associated
![image](https://user-images.githubusercontent.com/11287957/40135661-87253f14-594e-11e8-83b5-d4fe44cf03d9.png)

**Comment by clockworkgeek** [comment]
As of version 1.3.1, images are no longer required.  At least not in my testing.  Hopefully it works for you too.
