### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by mattdavenport** [clockworkgeek/Magento-Extra-RESTful#7]
I'm hoping the author is still around here, as this extension looks awesome! Nearly every feature included is part of my overall goal in extending the API, so thanks for the great work!

Unfortunately I'm having some issues in installation. I've added the module via modman to my existing Magento setup. However the code does not seem to be calling the included `Product.php` class on any requests to the API. I do see the additional attributes in the REST API system configuration, and I can even access extra endpoints such as `/stores`.

I'm currently running `v1.9.4.0`, so perhaps there were some updates to the core API that clobbered this module. I am failing to see where this module overwrites any read-based resources, as the only config rewrites are for the `Admin` classes which appear to only handle updating/writing.

Any idea where I could be going wrong or missing something here? Thanks!

**Comment by clockworkgeek** [comment]
Hello Matt,
Please see how this extension [requires a `Version` header](https://github.com/clockworkgeek/Magento-Extra-RESTful/blob/master/docs/Products.md#products) in the doc.

**Comment by mattdavenport** [comment]
@clockworkgeek Thanks for the prompt reply. I've attempted both `Version: 1` and `Version: 2` in this case. I'm admittedly not _that_ familiar with the API internals, although I've been learning quite a bit in the past few days.

I was attempting to move some things around to get this to work for me, and one method seemed to be creating a `Clockworkgeek_Extrarestful_Model_Api2_Product_Rest_Admin_V2` class that was empty but extended `Clockworkgeek_Extrarestful_Model_Api2_Product` and using that as the rewrite for `api2_product_rest_admin_v2`. This appears to have worked, but I don't want to change any code in this extension if I don't need to, so am investigating further.

Given that modification helped, does that give you any further context as to what could be happening here? Since you posted your comment, I've reverted back to the original `master` code and the same behavior is occurring (attribute labels are not resolved, requests going through `Mage_Catalog_Model_Api2_Product_Rest_Admin_V1` instead).

**Comment by clockworkgeek** [comment]
It might be relevant that you are using the Admin role. I only anticipated using that for create/update/delete stuff, and guest or customer roles for reading.

Your change is perfectly valid. If you wanted to do it neatly then create your own module with the same class rewrite in `config.xml` except with your module name. Also maybe add a `<depends>` clause in the module declaration file so it is initialised after this one.

**Comment by mattdavenport** [comment]
Thanks for all of the help! I'll continue down this road then, as I need full access to all system orders _and_ products so I think that is the best route. Once again, great module and thank you!
